### ISSUE TITLE
sources not refreshing

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/CdmAtlasCutover#1]
Thanks for the very useful package! I had been doing this by hand for a while!.

I have added a new source and executed the source refresh function but my sources in Atlas are still missing. Any ideas? I have Web API v2.0.0 and latest ATLAS.

**Comment by alondhe** [comment]
Hi Juan -- Good to hear! Did you clear cache or try in incognito?

Also, my latest commit addresses a small issue, the library dependencies weren't established correctly. Did you use this latest one?

**Comment by jmbanda** [comment]
Yes, using the latest one. I have flushed all cache, files, and even a
clean install of the browser. I have also stopped and started WebApi again.
Should I redeploy it?

On May 17, 2017 11:23 AM, "Ajit Londhe" <notifications@github.com> wrote:

Hi Juan -- Good to hear! Did you clear cache or try in incognito?

Also, my latest commit addresses a small issue, the library dependencies
weren't established correctly. Did you use this latest one?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OHDSI/CdmAtlasCutover/issues/1#issuecomment-302184078>,
or mute the thread

**Comment by alondhe** [comment]
So the sources are present in your SOURCE and SOURCE_DAIMON tables, but in Atlas->Config, you don't see them at all? Could you send those records (abstracted)?

**Comment by alondhe** [comment]
@jmbanda -- did we ever get this resolved?

**Comment by jmbanda** [comment]
Yes, after talking with Chris Knoll and learning his tricks, this was fixed
:)

_____________________________________________________________
Juan M. Banda, Ph.D.
NOTE: I am now an Assistant Professor at Georgia State University.
This email will stop working soon, so please update my contact email to:
jbanda@gsu.edu

Google Scholar: http://goo.gl/RiO2jY | ResearchGate: http://goo.gl/7C31uc
DBLP: http://goo.gl/BBvmJj | LinkedIn: http://goo.gl/bjkF8H
<https://goo.gl/bjkF8H> <http://goo.gl/h95tnq>
