### ISSUE TITLE
Should baseURL follow the rule of .checkBaseUrl

### ISSUE THREAD

**Issue by chandryou** [OHDSI/CdmAtlasCutover#4]
Hi, @alondhe 
I'm try to execute 'OhdsiRTool::insertCohortDefinitionSetInPackage'
And I'm suffering from '.checkBaseUrl'

```
.checkBaseUrl <- function(baseUrl)
  {
    return(grepl(pattern = "https?:\\/\\/[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})+(\\/.*)?\\/WebAPI$", 
                 x = baseUrl, 
                 ignore.case = FALSE))
  }
```

My WebAPI address looks like this:' http://128.1.99.100:8080/WebAPI'
It doesn't work because '**[a-z]{2,5}**'

Should baseURL follow the rule of .checkBaseUrl ??

Thank you!

**Comment by alondhe** [comment]
Hi @chandryou - will comment on this in the OhdsiRTools repo
